// <auto-generated />
using System;
using BudgetExperiment.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetExperiment.Infrastructure.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260113030114_AddAppSettings")]
    partial class AddAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetExperiment.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("InitialBalanceDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("BudgetExperiment.Domain.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoRealizePastDueItems")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PastDueLookbackDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AutoRealizePastDueItems = false,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PastDueLookbackDays = 30,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BudgetExperiment.Domain.RecurringTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("LastGeneratedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NextOccurrence")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("IsActive");

                    b.HasIndex("NextOccurrence");

                    b.ToTable("RecurringTransactions", (string)null);
                });

            modelBuilder.Entity("BudgetExperiment.Domain.RecurringTransactionException", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("OriginalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RecurringTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecurringTransactionId");

                    b.HasIndex("RecurringTransactionId", "OriginalDate")
                        .IsUnique();

                    b.ToTable("RecurringTransactionExceptions", (string)null);
                });

            modelBuilder.Entity("BudgetExperiment.Domain.RecurringTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("LastGeneratedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NextOccurrence")
                        .HasColumnType("date");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("IsActive");

                    b.HasIndex("NextOccurrence");

                    b.HasIndex("SourceAccountId");

                    b.ToTable("RecurringTransfers", (string)null);
                });

            modelBuilder.Entity("BudgetExperiment.Domain.RecurringTransferException", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("OriginalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RecurringTransferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecurringTransferId");

                    b.HasIndex("RecurringTransferId", "OriginalDate")
                        .IsUnique();

                    b.ToTable("RecurringTransferExceptions", (string)null);
                });

            modelBuilder.Entity("BudgetExperiment.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("RecurringInstanceDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("RecurringTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecurringTransferId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("RecurringTransferInstanceDate")
                        .HasColumnType("date");

                    b.Property<int?>("TransferDirection")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Date");

                    b.HasIndex("RecurringTransactionId");

                    b.HasIndex("RecurringTransferId");

                    b.HasIndex("TransferId");

                    b.HasIndex("AccountId", "Date");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("BudgetExperiment.Domain.Account", b =>
                {
                    b.OwnsOne("BudgetExperiment.Domain.MoneyValue", "InitialBalance", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("InitialBalance");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("InitialBalanceCurrency");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("InitialBalance")
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetExperiment.Domain.RecurringTransaction", b =>
                {
                    b.HasOne("BudgetExperiment.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetExperiment.Domain.MoneyValue", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RecurringTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("RecurringTransactionId");

                            b1.ToTable("RecurringTransactions");

                            b1.WithOwner()
                                .HasForeignKey("RecurringTransactionId");
                        });

                    b.OwnsOne("BudgetExperiment.Domain.RecurrencePattern", "RecurrencePattern", b1 =>
                        {
                            b1.Property<Guid>("RecurringTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("DayOfMonth")
                                .HasColumnType("integer")
                                .HasColumnName("DayOfMonth");

                            b1.Property<int?>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("DayOfWeek");

                            b1.Property<int>("Frequency")
                                .HasColumnType("integer")
                                .HasColumnName("Frequency");

                            b1.Property<int>("Interval")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(1)
                                .HasColumnName("Interval");

                            b1.Property<int?>("MonthOfYear")
                                .HasColumnType("integer")
                                .HasColumnName("MonthOfYear");

                            b1.HasKey("RecurringTransactionId");

                            b1.ToTable("RecurringTransactions");

                            b1.WithOwner()
                                .HasForeignKey("RecurringTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("RecurrencePattern")
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetExperiment.Domain.RecurringTransactionException", b =>
                {
                    b.HasOne("BudgetExperiment.Domain.RecurringTransaction", null)
                        .WithMany()
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetExperiment.Domain.MoneyValue", "ModifiedAmount", b1 =>
                        {
                            b1.Property<Guid>("RecurringTransactionExceptionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("ModifiedAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("ModifiedCurrency");

                            b1.HasKey("RecurringTransactionExceptionId");

                            b1.ToTable("RecurringTransactionExceptions");

                            b1.WithOwner()
                                .HasForeignKey("RecurringTransactionExceptionId");
                        });

                    b.Navigation("ModifiedAmount");
                });

            modelBuilder.Entity("BudgetExperiment.Domain.RecurringTransfer", b =>
                {
                    b.HasOne("BudgetExperiment.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetExperiment.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetExperiment.Domain.MoneyValue", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RecurringTransferId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("RecurringTransferId");

                            b1.ToTable("RecurringTransfers");

                            b1.WithOwner()
                                .HasForeignKey("RecurringTransferId");
                        });

                    b.OwnsOne("BudgetExperiment.Domain.RecurrencePattern", "RecurrencePattern", b1 =>
                        {
                            b1.Property<Guid>("RecurringTransferId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("DayOfMonth")
                                .HasColumnType("integer")
                                .HasColumnName("DayOfMonth");

                            b1.Property<int?>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("DayOfWeek");

                            b1.Property<int>("Frequency")
                                .HasColumnType("integer")
                                .HasColumnName("Frequency");

                            b1.Property<int>("Interval")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(1)
                                .HasColumnName("Interval");

                            b1.Property<int?>("MonthOfYear")
                                .HasColumnType("integer")
                                .HasColumnName("MonthOfYear");

                            b1.HasKey("RecurringTransferId");

                            b1.ToTable("RecurringTransfers");

                            b1.WithOwner()
                                .HasForeignKey("RecurringTransferId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("RecurrencePattern")
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetExperiment.Domain.RecurringTransferException", b =>
                {
                    b.HasOne("BudgetExperiment.Domain.RecurringTransfer", null)
                        .WithMany()
                        .HasForeignKey("RecurringTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetExperiment.Domain.MoneyValue", "ModifiedAmount", b1 =>
                        {
                            b1.Property<Guid>("RecurringTransferExceptionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("ModifiedAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("ModifiedCurrency");

                            b1.HasKey("RecurringTransferExceptionId");

                            b1.ToTable("RecurringTransferExceptions");

                            b1.WithOwner()
                                .HasForeignKey("RecurringTransferExceptionId");
                        });

                    b.Navigation("ModifiedAmount");
                });

            modelBuilder.Entity("BudgetExperiment.Domain.Transaction", b =>
                {
                    b.HasOne("BudgetExperiment.Domain.Account", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetExperiment.Domain.RecurringTransaction", null)
                        .WithMany()
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BudgetExperiment.Domain.RecurringTransfer", null)
                        .WithMany()
                        .HasForeignKey("RecurringTransferId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("BudgetExperiment.Domain.MoneyValue", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetExperiment.Domain.Account", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
